// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bsmygijczfasirrimoag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzbXlnaWpjemZhc2lycmltb2FnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQzNTg2NzYsImV4cCI6MjA5OTkzNDY3Nn0.6_aIjxp-uCIxfaRGtGD1uq5zdGg2P_ttZoFyT7D_3Ko";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});